# Generated by Django 4.2.1 on 2023-08-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_rename_chatroom_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='created',
        ),
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='members',
        ),
        migrations.RemoveField(
            model_name='room',
            name='updated',
        ),
    ]
