# Generated by Django 4.2.1 on 2023-08-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_remove_room_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.CharField(default=True, max_length=120),
        ),
    ]
