# Generated by Django 4.2.1 on 2023-07-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_userstatus_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='description',
            field=models.CharField(max_length=120),
        ),
    ]
