# Generated by Django 4.2.1 on 2023-07-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
